language: node_js
node_js:
  - lts/dubnium
  - node
sudo: false
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: SiWKLY50sxUTwuoWghsehPF3ZqjB8gG3Y/4mrXAXOe4dTbTyJSUGTvLvpyQrKjAfns7YHCuN7x85OleOEOMfMP+RHy6Gb+VcoqUS/PLzQNtNZj0wZMdiBSPYiC8hWx11ebg+TUbAxLbtXvUpRZODCU7bM0zpAvzT1AqaN2+zV4g=
  file:
    - 'markdown-table.js'
    - 'markdown-table.min.js'
  on:
    tags: true
